on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        id: checkout-folder
        run: mkdir -p dist
      - name: Hello world action step
        id: hello
        uses: harrisd19/docker-it-up@v12
        with:
          directory-input: 'dist'
          args: -v dist/:/usr/src/app/dist/
