on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: harrisd19/docker-it-up@v7
        with:
          who-to-greet: 'Devon :)'
