on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Add folder
        id: add-folder
        run: mkdir -p dist2
      - name: run docker-it-up action
        id: action
        uses: harrisd19/docker-it-up@v13
        runs:
          using: 'docker'
          image: 'Dockerfile'
          args:
            - --volume ${{ github.workspace }}/dist2:/usr/src/app/dist2/
            - ls -la /usr/src/app/