on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Add folder
        id: add-folder
        run: mkdir -p dist2
      - name: Run docker-it-up action
        id: action
<<<<<<< Updated upstream
        uses: harrisd19/docker-it-up@v15
=======
        uses: harrisd19/docker-it-up@v16
>>>>>>> Stashed changes
        with:
          directory-input: 'dist2'
